version: "3.9"
services:
  frontend:
    container_name: nginx-frontend-app
    image: maestro_frontend
    restart: always
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        NODE_ENV: development
        BACKEND_DEV_HOST: http://localhost:80/api
    env_file:
      - .env
    volumes:
      - ./infra/nginx/conf/:/etc/nginx/conf.d/:ro
    networks:
      - natbridge
    ports:
      - 80:80
      - 443:443

  backend:
    container_name: node-app
    image: maestro_backend
    restart: always
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - FRONTEND_DEV_HOST=http://localhost:80
    networks:
      - natbridge

networks:
  natbridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/24
